services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    networks:
      - my-bridge

  cafe-com-type:
    build:
      context: .
      dockerfile: Dockerfile
    image: renancesu/cafe-com-type:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - NODEMAILER_TEST_HOST=${NODEMAILER_TEST_HOST}
      - NODEMAILER_TEST_EMAIL=${NODEMAILER_TEST_EMAIL}
      - NODEMAILER_TEST_PASS=${NODEMAILER_TEST_PASS}
    depends_on:
      - postgres
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge
