name: 'Push para o Docker Hub'

on:
  push:
    branches:
      - main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: programa
          path: ./artefatos/cafe-com-type.tar

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: renancesu
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./artefatos
          file: ./artefatos/Dockerfile
          push: true
          tags: renancesu/cafe-com-type:${{ github.ref_name }}