name: 'Push para o DockerHub'

on:
  workflow_run:
    workflows: ['Buildar o artefato da imagem Docker']
    types:
      - completed

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: cafe-com-type
          path: ./artefatos

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: renancesu
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Load Docker image from artifact
        run: |
          docker load -i ./artefatos/cafe-com-type.tar

      - name: Push Docker image with dynamic tag to Docker Hub
        run: |
          docker tag renancesu/cafe-com-type renancesu/cafe-com-type:${{ github.sha }}
          docker push renancesu/cafe-com-type:${{ github.sha }}

      - name: Push Docker image with latest tag to Docker Hub
        run: |
          docker tag renancesu/cafe-com-type renancesu/cafe-com-type:latest
          docker push renancesu/cafe-com-type:latest
