name: 'Push para Docker Hub'

on:
  push:
    branches:
      - main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: cafe-com-type

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: renancesu
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Load Docker image from artifact
        run: |
          docker load -i cafe-com-type.tar

      - name: Push Docker image to Docker Hub
        run: |
          docker tag renancesu/cafe-com-type:latest renancesu/cafe-com-type:latest
          docker push renancesu/cafe-com-type:latest
